server:
  port: 8080

spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:accounts_service}${DB_URL_PARAM:?ssl=false}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10

jwt:
  issuer: ${JWT_ISSUER:thiago-magdalena}
  secret: ${JWT_SECRET:4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4PT}

security:
  post-public-paths:
    - "/users"
    - "/users/login"
  public-paths:
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/webjars/**"
    - "/swagger-resources/**"